routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('main');
});

Route::get('about', function () {
    return view('about');
});

Route::get('contact', function () {
    return view('contact');
});

Route::get('login', function () {
    return view('login');
});

Route::get('/', 'PagesController@getIndex');
Route::get('contact', 'PagesController@getContact');
Route::get('about', 'PagesController@getAbout');
//Route::get('login', 'PagesController@getLogin');
//Route::get('register', 'PagesController@getRegister');
Route::get('admin', 'RolesController@store');
Route::get('edit', 'PagesController@getEdit');

Route::resource('/userprofile','userProfileController');
Route::get('/userprofile','userProfileController@create');
//Route::get('/userprofile/{id}/edit', ['as' => 'userprofile.edit', 'uses' => 'userProfileController@edit']);
Route::get('/userprofile/{id}/edit', 'userProfileController@edit');
Route::post('/userprofile/{id}', 'userProfileController@update');
Route::get('/userprofile/{id}', 'userProfileController@show');
//Route::get('/userprofile/changePassword', 'userProfileController@changePassword');
Route::get('/resetpass/{id}/index', 'ResetPasswordController@changePassword');
Route::post('/resetpass/{id}', 'ResetPasswordController@update');
Route::resource('resetpass', 'ResetPasswordController');
Route::get('search', 'PagesController@getSearch');
//Route::get('findUser', 'PagesController@getUser');

Route::match(['get','post'],'findUser', 'SearchController@findUser');
Route::match(['get','post'],'findUser', 'SearchController@findUser');
Route::get('updateData', 'PagesController@getUpdateData');

Route::resource('posts', 'PostController');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'web'], function () {
    Route::get('/', function () {
        return view('index');
    })->name('main');
    
    Route::get('/author', [
        'uses' => 'AppController@getAuthorPage',
        'as' => 'author',
        'middleware' => 'roles',
        'roles' => ['Admin', 'Author']
    ]);
    
    Route::get('/author/generate-article', [
        'uses' => 'AppController@getGenerateArticle',
        'as' => 'author.article',
        'middleware' => 'roles',
        'roles' => ['Author']
    ]);
    
    Route::get('/admin', [
        'uses' => 'AppController@getAdminPage',
        'as' => 'admin',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);
    
    Route::post('/admin/assign-roles', [
        'uses' => 'AppController@postAdminAssignRoles',
        'as' => 'admin.assign',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);
    
    });

resources/views/resetpass/index.blade.php
@extends('main')

@section('content')

  <form class="form-horizontal" role="form" method="post" action="{{ route('resetpass.update', Auth::user()->id) }}" >
            {{ csrf_field() }}

          <div class="form-group">
            <label class="col-lg-3 control-label">Password:</label>
            <div class="col-lg-8">
                <input class="form-control" value="" type="password" name="password">
            </div>
          </div>

         <div class="form-group">
            <label class="col-lg-3 control-label">New password:</label>
            <div class="col-lg-8">
                <input class="form-control" value="" type="password" name="newpassword">
            </div>
            
          </div>
        <div class="form-group">
            <label class="col-lg-3 control-label">Confirm your password:</label>
            <div class="col-lg-8">
                <input class="form-control" value="" type="password" name="confPassword">
            </div>
          </div>
            
          <div class="form-group">
            <label class="col-md-3 control-label"></label>
            <div class="col-md-8">
              <input class="btn btn-primary" value="Save changes" type="submit">
              <span></span>
              <input class="btn btn-default" value="Cancel" type="reset">
            </div>
          </div>
        </form>

<hr>

@endsection